# File Creation
REPORTS_PATH = "./reports"
RESULTS_PATH = "./results"
RESULT_FILE_NAME_SUFFIX = "_RESULT"

# unit lables
RSSI_UNIT = 'dBm'
RSRP_UNIT = 'dBm'
RSRQ_UNIT = 'dB'

# result descriptions
EXCELLENT_RESULT = 'Excellent'
GOOD_RESULT = 'Good'
FAIR_RESULT = 'Fair'
POOR_RESULT = 'Poor'
UNUSABLE_RESULT = 'Unusable'

# Thresholds for report evaluation
bounds = {
    #boundary name          : (value, unit, ranking, above boundary result description, below boundary result description)
    "RSSI_EXCLNT_GOOD_BOUND": (-59, RSSI_UNIT, 0, EXCELLENT_RESULT, GOOD_RESULT),
    "RSSI_GOOD_FAIR_BOUND" : (-69, RSSI_UNIT, 1, GOOD_RESULT, FAIR_RESULT),
    "RSSI_FAIR_POOR_BOUND" : (-74, RSSI_UNIT, 2, FAIR_RESULT, POOR_RESULT),
    "RSSI_POOR_UNUSBL_BOUND" : (-79, RSSI_UNIT, 3, POOR_RESULT, UNUSABLE_RESULT),

    "RSRP_EXCLNT_GOOD_BOUND" : (-79, RSRP_UNIT, 0, EXCELLENT_RESULT, GOOD_RESULT),
    "RSRP_GOOD_FAIR_BOUND" : (-89, RSRP_UNIT, 1, GOOD_RESULT, FAIR_RESULT),
    "RSRP_FAIR_POOR_BOUND" : (-109, RSRP_UNIT, 2, FAIR_RESULT, POOR_RESULT),
    "RSRP_POOR_UNUSBL_BOUND" : (-119, RSRP_UNIT, 3, POOR_RESULT, UNUSABLE_RESULT),


    "RSRQ_EXCLNT_GOOD_BOUND" : (-5, RSRQ_UNIT, 0, EXCELLENT_RESULT, GOOD_RESULT),
    "RSRQ_GOOD_FAIR_BOUND" : (-8, RSRQ_UNIT, 1, GOOD_RESULT, FAIR_RESULT),
    "RSRQ_FAIR_POOR_BOUND" : (-10, RSRQ_UNIT, 2, FAIR_RESULT, POOR_RESULT),
    "RSRQ_POOR_UNUSBL_BOUND" : (-19, RSRQ_UNIT, 3, POOR_RESULT, UNUSABLE_RESULT),
}


